services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_SRV=${MONGODB_SRV}
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

